sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pouannes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pouannes/docker-react npm run test
